import type { UserRole } from '../domain/enums.js';

export const PERMISSIONS = [
  'platform.manage',
  'platform.impersonate',
  'platform.viewAudit',
  'ruleset.manage',
  'ruleset.view',
  'org.manage',
  'org.view',
  'org.users.manage',
  'shooter.manage',
  'shooter.edit',
  'shooter.view',
  'match.create',
  'match.edit',
  'match.configure',
  'match.publish',
  'match.manage',
  'match.view',
  'match.archive',
  'stage.manage',
  'squad.manage',
  'competitor.manage',
  'checkin.manage',
  'chronograph.manage',
  'score.enter',
  'score.edit',
  'score.submit',
  'score.verify',
  'score.lock',
  'score.unlock',
  'score.correct',
  'score.view',
  'score.audit',
  'disputes.manage',
  'reports.generate',
  'results.live',
  'results.public',
  'profile.own',
  'dispute.raise.own',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  PLATFORM_SUPER_ADMIN: [...PERMISSIONS],
  PLATFORM_ADMIN: [
    'platform.manage',
    'platform.viewAudit',
    'ruleset.manage',
    'ruleset.view',
    'org.view',
    'org.manage',
    'org.users.manage',
    'shooter.view',
    'shooter.manage',
    'shooter.edit',
    'match.view',
    'match.archive',
    'score.view',
    'score.enter',
    'score.edit',
    'score.submit',
    'score.verify',
    'score.lock',
    'score.unlock',
    'score.correct',
    'score.audit',
  ],
  ORGANIZATION_ADMIN: [
    'org.view',
    'org.manage',
    'org.users.manage',
    'shooter.view',
    'shooter.manage',
    'match.create',
    'match.edit',
    'match.configure',
    'match.publish',
    'match.manage',
    'match.view',
    'stage.manage',
    'squad.manage',
    'competitor.manage',
    'checkin.manage',
    'chronograph.manage',
    'score.enter',
    'score.edit',
    'score.submit',
    'score.verify',
    'score.lock',
    'score.unlock',
    'score.correct',
    'score.view',
    'score.audit',
    'disputes.manage',
    'reports.generate',
    'results.live',
    'results.public',
    'ruleset.view',
  ],
  MATCH_DIRECTOR: [
    'match.view',
    'match.edit',
    'match.configure',
    'match.publish',
    'match.archive',
    'shooter.manage',
    'shooter.view',
    'stage.manage',
    'squad.manage',
    'competitor.manage',
    'checkin.manage',
    'chronograph.manage',
    'score.view',
    'score.enter',
    'score.edit',
    'score.submit',
    'score.correct',
    'disputes.manage',
    'reports.generate',
    'results.live',
    'results.public',
    'shooter.view',
  ],
  RANGE_MASTER: [
    'match.view',
    'score.view',
    'score.verify',
    'score.lock',
    'score.unlock',
    'score.correct',
    'score.audit',
    'disputes.manage',
  ],
  RANGE_OFFICER: [
    'match.view',
    'score.enter',
    'score.edit',
    'score.submit',
    'stage.manage',
    'squad.manage',
  ],
  SCOREKEEPER: ['match.view', 'score.enter', 'score.view', 'score.submit'],
  COMPETITOR: ['results.public', 'profile.own', 'dispute.raise.own', 'match.view'],
  VIEWER: ['results.public', 'match.view'],
};

export function roleHasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export const ROLE_LABELS: Record<UserRole, string> = {
  PLATFORM_SUPER_ADMIN: 'Platform Super Administrator',
  PLATFORM_ADMIN: 'Platform Administrator',
  ORGANIZATION_ADMIN: 'Organization Administrator',
  MATCH_DIRECTOR: 'Match Director',
  RANGE_MASTER: 'Range Master',
  RANGE_OFFICER: 'Range Officer',
  SCOREKEEPER: 'Scorekeeper',
  COMPETITOR: 'Competitor',
  VIEWER: 'Viewer',
};

export function hasAnyRole(roles: UserRole[], permission: Permission): boolean {
  return roles.some((r) => roleHasPermission(r, permission));
}