import type { Db } from '../db/client.js';
import { listStages } from './stages.js';
import { listScores, scoreView, type ScoreWithCompetitor } from './scores.js';
import { computeMatchStandings, getStageResults } from './results.js';
import { matchView } from './matches.js';
import { isTimeScoringMethod, type Match } from '@blinkscore/core';

function esc(value: unknown): string {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function csvCell(value: unknown): string {
  const s = value === null || value === undefined ? '' : String(value);
  return `"${s.replace(/"/g, '""')}"`;
}

function csvRow(cells: unknown[]): string {
  return cells.map(csvCell).join(',');
}

export function matchResultsCsv(db: Db, match: Match): string {
  const standings = computeMatchStandings(db, match, { persist: true });
  const lines: string[] = [csvRow(['Match', esc(match.name), 'Date', match.startDate])];
  lines.push(csvRow(['Rank', 'Shooter', 'Division', 'Category', 'Power Factor', 'Match Number', 'Total Points', 'Tie']));
  for (const row of standings.overall) {
    lines.push(
      csvRow([
        row.rankDisplay,
        row.shooterName,
        row.divisionName ?? '',
        row.categoryName ?? row.categoryId ?? '',
        row.declaredPowerFactor,
        row.matchNumber ?? '',
        row.matchTotal,
        row.tie ? 'TIE' : '',
      ]),
    );
  }
  return lines.join('\n');
}

export function matchScorecardsCsv(db: Db, match: Match): string {
  const stages = listStages(db, match);
  const lines: string[] = [csvRow(['Stage', 'Shooter', 'Time', 'Raw', 'Penalties', 'Net', 'Hit Factor', 'Time Adjust', 'Final Time', 'Status', 'Verified'])];
  for (const stage of stages) {
    const timeScoring = isTimeScoringMethod(stage.scoringMethod);
    const scores: ScoreWithCompetitor[] = listScores(db, match, { stageId: stage.id });
    for (const s of scores) {
      lines.push(
        csvRow([
          `${stage.number}. ${stage.name}`,
          s.shooterName,
          s.timeSeconds,
          s.rawPoints,
          s.penaltyPoints,
          s.netPoints,
          timeScoring ? '' : s.hitFactor,
          timeScoring ? s.timeAdjustmentsSeconds : '',
          timeScoring ? s.finalTimeSeconds : '',
          s.status,
          s.verifiedAt ?? '',
        ]),
      );
    }
  }
  return lines.join('\n');
}

export function standingsHtml(db: Db, match: Match): string {
  const standings = computeMatchStandings(db, match);
  const view = matchView(db, match);
  const rows = standings.overall
    .map(
      (r) =>
        `<tr class="${r.tie ? 'tie' : ''}"><td class="rank">${esc(r.rankDisplay)}</td><td>${esc(r.shooterName)}</td><td>${esc(r.divisionName ?? '')}</td><td class="num">${r.matchTotal.toFixed(3)}</td></tr>`,
    )
    .join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${esc(match.name)} — Results</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;margin:2rem;color:#222}
  h1{margin-bottom:.25rem}h2{color:#555;font-weight:400;margin-top:0}
  table{border-collapse:collapse;width:100%;margin-top:1rem}
  th,td{border-bottom:1px solid #ddd;padding:.5rem .75rem;text-align:left}
  th{background:#f4f4f4}td.num{text-align:right}td.rank{font-weight:600;color:#0a66c2}
  tr.tie{background:#fffbe6}.tie{color:#a05c00}
  @media print{ body{margin:.5in} th,td{padding:.25rem .5rem} }
</style></head><body>
<h1>${esc(match.name)}</h1><h2>${esc(view.venue ?? '')} — ${esc(match.startDate)}</h2>
<table><thead><tr><th>Rank</th><th>Shooter</th><th>Division</th><th class="num">Total</th></tr></thead>
<tbody>${rows}</tbody></table>
<p style="margin-top:2rem;color:#777;font-size:.8rem">Generated by PPSA Match Scorer — ${esc(new Date().toISOString())}</p>
</body></html>`;
}

export function stageScorecardsHtml(db: Db, match: Match): string {
  const stages = listStages(db, match);
  const sections = stages
    .map((stage) => {
      const timeScoring = isTimeScoringMethod(stage.scoringMethod);
      const details = getStageResults(db, match, stage.id);
      const scores = listScores(db, match, { stageId: stage.id });
      const rows = scores
        .map((s) => {
          const v = scoreView(s);
          const cols = timeScoring
            ? `<td class="num">${v.finalTimeSeconds ?? ''}</td><td class="num">${v.timeAdjustmentsSeconds ?? ''}</td>`
            : `<td class="num">${v.netPoints ?? ''}</td><td class="num">${v.hitFactor ?? ''}</td>`;
          return `<tr><td>${esc(s.shooterName)}</td><td class="num">${v.timeSeconds ?? ''}</td><td class="num">${v.rawPoints ?? ''}</td><td class="num">${v.penaltyPoints ?? ''}</td>${cols}<td>${esc(s.status)}</td></tr>`;
        })
        .join('');
      const header = timeScoring
        ? '<tr><th>Shooter</th><th class="num">Time</th><th class="num">Raw</th><th class="num">Pens</th><th class="num">Final</th><th class="num">Adj</th><th>Status</th></tr>'
        : '<tr><th>Shooter</th><th class="num">Time</th><th class="num">Raw</th><th class="num">Pens</th><th class="num">Net</th><th class="num">HF</th><th>Status</th></tr>';
      return `<h3>Stage ${stage.number}: ${esc(stage.name)}</h3><table><thead>${header}</thead><tbody>${rows}</tbody></table>`;
    })
    .join('');
  return standardReportHtml(match, sections, 'Scorecards');
}

export function certificatesHtml(db: Db, match: Match): string {
  const standings = computeMatchStandings(db, match);
  const boxes = standings.overall.slice(0, 5).map((r, i) => {
    const place = ['1st', '2nd', '3rd', '4th', '5th'][i];
    return `<div class="cert"><h3>${place} Place</h3><p class="name">${esc(r.shooterName)}</p><p>${esc(match.name)} — Overall, ${r.matchTotal.toFixed(3)} points</p></div>`;
  }).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Certificates — ${esc(match.name)}</title>
<style>
  body{font-family:Georgia,serif;margin:2rem;color:#222}
  .cert{border:2px solid #b8860b;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem;text-align:center;background:#fffdf5}
  .cert h3{color:#8b6914;text-transform:uppercase;letter-spacing:.08em}
  .cert .name{font-size:1.6rem;margin:.5rem 0}
  @media print{ .cert{page-break-inside:avoid} }
</style></head><body>
<h1 style="text-align:center">PPSA Match Scorer — Certificates</h1>
${boxes}
<p style="text-align:center;color:#777;font-size:.8rem">Generated ${esc(new Date().toISOString())}</p>
</body></html>`;
}

function standardReportHtml(match: Match, body: string, title: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${esc(match.name)} — ${esc(title)}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;margin:2rem;color:#222}
  h1{margin-bottom:.25rem}h2{color:#555;font-weight:400}
  table{border-collapse:collapse;width:100%;margin-bottom:1.5rem}
  th,td{border-bottom:1px solid #ddd;padding:.4rem .6rem;text-align:left}
  th{background:#f4f4f4}td.num{text-align:right}
  @media print{ body{margin:.5in} th,td{padding:.2rem .4rem} }
</style></head><body><h1>${esc(match.name)}</h1><h2>${esc(title)}</h2>${body}</body></html>`;
}